export const GET_ACTIVEDIRECTORIES = 'GET_ACTIVEDIRECTORIES'
export const CREATE_ACTIVEDIRECTORY = 'CREATE_ACTIVEDIRECTORY'
export const EDIT_ACTIVEDIRECTORY = 'EDIT_ACTIVEDIRECTORY'
export const DELETE_ACTIVEDIRECTORY = 'DELETE_ACTIVEDIRECTORY'