export const GET_LOADBALANCER_FARMS = 'GET_LOADBALANCER_FARMS';
export const SET_LOADBALANCER_POOL_STATUS = 'SET_LOADBALANCER_POOL_STATUS';
export const SET_LOADBALANCER_POOL_STATUS_LOADING = 'SET_LOADBALANCER_POOL_STATUS_LOADING';
