export const GET_DISME_APPLICATIONS = 'GET_DISME_APPLICATIONS';

export const GET_SERVICE_DETAILS_BY_SHORTCUTS = 'GET_SERVICE_DETAILS_BY_SHORTCUTS';

export const REMOVE_SERVICE_DETAILS = 'REMOVE_SERVICE_DETAILS';

export const GET_ROLLOUT_STATUS = 'GET_ROLLOUT_STATUS';