export const GET_DISME_APPLICATIONS = 'GET_DISME_APPLICATIONS';

export const GET_ROLLOUT_STATUS = 'GET_ROLLOUT_STATUS';

export const DELETE_ALL_ROLLOUT_STATUSES = 'DELETE_ALL_ROLLOUT_STATUSES';

export const REMOVE_ROLLOUT_STATUS = 'REMOVE_ROLLOUT_STATUS';