export const GET_DISME_APPLICATIONS = 'GET_DISME_APPLICATIONS';

export const GET_SERVICE_DETAILS_BY_SHORTCUTS = 'GET_SERVICE_DETAILS_BY_SHORTCUTS';

export const REMOVE_SERVICE_DETAILS = 'REMOVE_SERVICE_DETAILS';

export const GET_ROLLOUT_STATUS = 'GET_ROLLOUT_STATUS';

export const DELETE_ALL_ROLLOUT_STATUSES = 'DELETE_ALL_ROLLOUT_STATUSES';

export const DELETE_ROLLOUT_STATUS = 'DELETE_ROLLOUT_STATUS';