export const GET_SERVICE_DETAILS = 'GET_SERVICE_DETAILS';

export const TOGGLE_LOADBALANCERFARMS_TASKS = 'TOGGLE_LOADBALANCERFARMS_TASKS';

export const GET_SERVICES = 'GET_SERVICES';

export const GET_HEALTH = 'GET_HEALTH';

export const GET_VERSION = 'GET_VERSION';

export const GET_SERVICE_DETAILS_BY_SHORTCUTS = 'GET_SERVICE_DETAILS_BY_SHORTCUTS';

export const REMOVE_SERVICE_DETAILS = 'REMOVE_SERVICE_DETAILS';

export const REMOVE_ALL_SERVICE_DETAILS = 'REMOVE_ALL_SERVICE_DETAILS';