export const GET_SERVER_DETAILS = 'GET_SERVER_DETAILS';

export const GET_VM_DETAILS = 'GET_VM_DETAILS';

export const GET_SERVER_SCOM_ALERTS = 'GET_SERVER_SCOM_ALERTS';

export const GET_SERVERS = 'GET_SERVERS';

export const GET_SERVER_STATS = 'GET_SERVER_STATS';

