export const SEARCH_SERVERS = 'SEARCH_SERVERS'

export const SEARCH_SERVICE_SHORTCUTS = 'SEARCH_SERVICE_SHORTCUTS'

export const TOGGLE_VERTICAL_MENU = 'TOGGLE_VERTICAL_MENU'

export const TOGGLE_USER_DETAILS = 'TOGGLE_USER_DETAILS'